### PR TITLE
Add Java to enabled apps

### PR DESCRIPTION
**Pull request by dborsatto**

### CODE REVIEW

**Comment by axe312ger** [comment]
😱 🙀 😱 🙀 😱 🙀 😱 🙀

**Comment by axe312ger** [comment]
Looks fine but I'd wait till java is done so we are not blocking CI's of other languages.

**Comment by Roblinde** [comment]
I have branches to add Java for csharp and python, will push them as soon as this is merged.

**Comment by dborsatto** [comment]
I think we can merge this.
We will wait to push to production each app, but in the meanwhile we're ready with the changes on master..

**Pull request merged**
